server:
  port: 10000

spring:


  application:
    name: yrz-eureka
  security:
    user:
      password: kaname
      name: kaname
  mvc:
    favicon:
      enabled: false

eureka:
  client:
    service-url:
      #多个地址用， 分割开
      defaultZone: http://kaname:kaname@localhost:10000/eureka

    # 表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: false

    # 表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: false